default:
	./parse.rb baldy <raw/baldy_run_to_the_top_2017.txt >times/baldy_run_to_the_top_2017.json
	./parse.rb baldy <raw/baldy_run_to_the_top_2018.txt >times/baldy_run_to_the_top_2018.json
	./parse.rb athlinks <raw/mt_wilson_trail_race_2018.txt >times/mt_wilson_trail_race_2018.json 
	./parse.rb athlinks <raw/mt_wilson_trail_race_2019.txt >times/mt_wilson_trail_race_2019.json 
	./parse.rb athlinks <raw/broken_arrow_vk_2019.txt >times/broken_arrow_vk_2019.json
	./parse.rb ultrasignup <raw/flagstaff_sky_peaks_vk_2017.txt >times/flagstaff_sky_peaks_vk_2017.json
	./parse.rb athlinks <raw/pasadena_half_marathon_2020.txt >times/pasadena_half_marathon_2020.json
	./parse.rb athlinks <raw/pasadena_half_marathon_2019.txt >times/pasadena_half_marathon_2019.json
	./parse.rb athlinks <raw/pasadena_half_marathon_2018.txt >times/pasadena_half_marathon_2018.json
	./parse.rb athlinks <raw/pasadena_half_marathon_2017.txt >times/pasadena_half_marathon_2017.json
	./parse.rb agoura <raw/agoura_chesebro_half_2019.txt >times/agoura_chesebro_half_2019.json
	./parse.rb into_the_wild1 <raw/into_the_wild_half_2017.txt >times/into_the_wild_half_2017.json
	./parse.rb into_the_wild2 <raw/into_the_wild_half_2018.txt >times/into_the_wild_half_2018.json
	./parse.rb into_the_wild2 <raw/into_the_wild_half_2019.txt >times/into_the_wild_half_2019.json
	./parse.rb ultrasignup <raw/griffith_park_30k_2019.txt >times/griffith_park_30k_2019.json
	./parse.rb ultrasignup <raw/griffith_park_30k_2018.txt >times/griffith_park_30k_2018.json
	./parse.rb revel <raw/revel_big_bear_half_2018.txt >times/revel_big_bear_half_2018.json
	./parse.rb revel <raw/revel_big_bear_half_2019.txt >times/revel_big_bear_half_2019.json
	./parse.rb revel <raw/revel_canyon_city_half_2014.txt >>times/revel_canyon_city_half_2014.json
	./parse.rb revel <raw/revel_canyon_city_half_2015.txt >>times/revel_canyon_city_half_2015.json
	./parse.rb revel <raw/revel_canyon_city_half_2016.txt >>times/revel_canyon_city_half_2016.json
	./parse.rb revel <raw/revel_canyon_city_half_2017.txt >>times/revel_canyon_city_half_2017.json
	./parse.rb runsignup <raw/irvine_half_2019.txt >times/irvine_half_2019.json
	./parse.rb athlinks <raw/santa_monica_classic_10k_2019.txt >times/santa_monica_classic_10k_2019.json

	


